- arguments:
  - "-XConstraintKinds"
  - "-XDeriveGeneric"
  - "-XGeneralizedNewtypeDeriving"
  - "-XLambdaCase"
  - "-XOverloadedStrings"
  - "-XRecordWildCards"
  - "-XScopedTypeVariables"
  - "-XStandaloneDeriving"
  - "-XTupleSections"
  - "-XTypeApplications"
  - "-XViewPatterns"
- ignore:
    name: Use head
- ignore:
    name: Use Foldable.forM_
- ignore:
    name: Use newtype instead of data
